// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `irc_logs` table.
    ///
    /// (Automatically generated by Diesel.)
    irc_logs (id) {
        /// The `id` column of the `irc_logs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `channel` column of the `irc_logs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        channel -> Varchar,
        /// The `ts` column of the `irc_logs` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        ts -> Timestamp,
        /// The `user_id` column of the `irc_logs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Int4,
        /// The `server_id` column of the `irc_logs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        server_id -> Int4,
        /// The `raw_line` column of the `irc_logs` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        raw_line -> Text,
    }
}

diesel::table! {
    /// Representation of the `irc_servers` table.
    ///
    /// (Automatically generated by Diesel.)
    irc_servers (id) {
        /// The `id` column of the `irc_servers` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `server_name` column of the `irc_servers` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        server_name -> Varchar,
    }
}

diesel::table! {
    /// Representation of the `irc_users` table.
    ///
    /// (Automatically generated by Diesel.)
    irc_users (id) {
        /// The `id` column of the `irc_users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `nickname` column of the `irc_users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        nickname -> Varchar,
        /// The `username` column of the `irc_users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        username -> Nullable<Varchar>,
        /// The `first_seen` column of the `irc_users` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        first_seen -> Timestamp,
    }
}

diesel::joinable!(irc_logs -> irc_servers (server_id));
diesel::joinable!(irc_logs -> irc_users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    irc_logs,
    irc_servers,
    irc_users,
);
